debug:
  enabled: false

message:
  command:
    create:
      setup:
        first: "&ePlease right-click the &abottom-left corner &eof the menu"
        second: "&ePlease right-click the &atop-right corner &eof the menu"
        set:
          first: "&aFirst corner set"
          second: "&aSecond corner set"
        complete: "&aSetup complete! &eCreating menu '%s' with script '%s'..."
        created: "&aMenu created."
    remove:
      removed: "&aMenu removed"
    reload:
      reloaded: "&aMenu script reloaded"
    download:
      loaded: "&aFile downloaded."
    error:
      create:
        exists: "&cMenu already exists"
        unknownScript: "&cThat script does not exist"
      remove:
        notFound: "&cMenu not found"
      download:
        invalidType: "&cInvalid file type"
        fileExists: "&cTarget file already exists. Please specify a different name."
        failed: "&cDownload failed. The source is no valid URL or File"
        exception: "&cUnexpected exception while downloading. See console for details."